### ISSUE TITLE
【报错】导入插件失败……？

### ISSUE THREAD

**Issue by BMC-Gordon0921** [s52047qwas/nonebot_plugin_xiuxian#107]
环境：Ubuntu 22.04（LTS），Python3.9.8，nonebot-2.0.0-rc1
*由于租不起服务器，就拿了手机改服务器，所谓Ubuntu其实是termux模拟的（）
问题描述：经由pip安装本插件后使用bot.py导入，在启动时报错。奇怪的是，这个插件在我Windows上跑的好好的（Python3.9.7），啥事没有……
详细报错代码：
11-12 23:38:38 [ERROR] nonebot | Failed to import "nonebot_plugin_xiuxian"
Traceback (most recent call last):
  File "/usr/local/bin/nb", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/nb_cli/commands/main.py", line 30, in run
    run_bot(file, app)
  File "/usr/local/lib/python3.9/site-packages/nb_cli/handlers/deploy.py", line 20, in run_bot
    module = importlib.import_module(module_name)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/root/??/bot_linux/./bot.py", line 31, in <module>
    nonebot.load_plugin('nonebot_plugin_xiuxian')
  File "/usr/local/lib/python3.9/site-packages/nonebot/plugin/load.py", line 34, in load_plugin
    return manager.load_plugin(module_path)
> File "/usr/local/lib/python3.9/site-packages/nonebot/plugin/manager.py", line 141, in load_plugin
    module = importlib.import_module(name)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "/usr/local/lib/python3.9/site-packages/nonebot/plugin/manager.py", line 233, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/local/lib/python3.9/site-packages/nonebot_plugin_xiuxian/__init__.py", line 33, in <module>
    scheduler = require("nonebot_plugin_apscheduler").scheduler
  File "/usr/local/lib/python3.9/site-packages/nonebot/plugin/load.py", line 167, in require
    raise RuntimeError(f'Cannot load plugin "{name}"!')
RuntimeError: Cannot load plugin "nonebot_plugin_apscheduler"!
所有资源文件已经安装到位，nonebot_plugin_apscheduler版本为0.2.0（0.1.4），无论如何均报错。
不知道是系统问题还是插件问题又或者是什么奇奇怪怪的问题了……

**Comment by Shinoakii** [comment]
nonebot_plugin_apscheduler这个更新下试试

**Comment by BMC-Gordon0921** [comment]
> nonebot_plugin_apscheduler这个更新下试试

【回复作者】看了一下官网版本，在pip已经把nonebot_plugin_apscheduler升级到0.2.0，但运行依旧报错（）报错代码仍旧如上所示，两份报错代码均一致，不同点就是nonebot_plugin_apschrduler版本的不同

**Comment by BMC-Gordon0921** [comment]
升级以后翻了翻错误代码，好像找到问题了，可能是apscheduler的配置在linux下没读出来就没有引入，给我报了一个
`Value Error：Zone info keys must be normalized relative paths，`
但不很理解应该怎么加.env的配置（）

**Comment by BMC-Gordon0921** [comment]
> Value Error：Zone info keys must be normalized relative paths，

感觉没踩上重点，是pytz报了时区错误，感觉可能要在源代码修改……？
错误信息：
```
pytz_deprecation_shim._exceptions._make_pytz_derived_errors.<locals>.UnknownTimeZoneError:''
```

**Comment by BMC-Gordon0921** [comment]
跑了一大圈还是没找到问题，把输出的所有报错端给大佬请求喂饭（bushi）努力寻找资料解决，希望佬可以帮帮忙
11-13 12:31:07 [ERROR] nonebot | Failed to import "nonebot_plugin_apscheduler"
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/pytz_deprecation_shim/_compat_py3.py", line 16, in get_timezone
    return zoneinfo.ZoneInfo(key)
  File "/usr/local/lib/python3.9/zoneinfo/_tzpath.py", line 67, in find_tzfile
    _validate_tzfile_path(key)
  File "/usr/local/lib/python3.9/zoneinfo/_tzpath.py", line 91, in _validate_tzfile_path
    raise ValueError(
ValueError: ZoneInfo keys must be normalized relative paths, got: 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/pytz_deprecation_shim/_impl.py", line 39, in timezone
    zone = _compat.get_timezone(key)
  File "/usr/local/lib/python3.9/site-packages/pytz_deprecation_shim/_compat_py3.py", line 19, in get_timezone
    raise KeyError(key)
KeyError: ''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/??/bot_linux/bot.py", line 31, in <module>
    nonebot.load_plugin('nonebot_plugin_xiuxian')
  File "/usr/local/lib/python3.9/site-packages/nonebot/plugin/load.py", line 34, in load_plugin
    return manager.load_plugin(module_path)
  File "/usr/local/lib/python3.9/site-packages/nonebot/plugin/manager.py", line 141, in load_plugin
    module = importlib.import_module(name)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "/usr/local/lib/python3.9/site-packages/nonebot/plugin/manager.py", line 233, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/local/lib/python3.9/site-packages/nonebot_plugin_xiuxian/__init__.py", line 33, in <module>
    scheduler = require("nonebot_plugin_apscheduler").scheduler
  File "/usr/local/lib/python3.9/site-packages/nonebot/plugin/load.py", line 163, in require
    plugin = manager.load_plugin(name)
> File "/usr/local/lib/python3.9/site-packages/nonebot/plugin/manager.py", line 141, in load_plugin
    module = importlib.import_module(name)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "/usr/local/lib/python3.9/site-packages/nonebot/plugin/manager.py", line 233, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/local/lib/python3.9/site-packages/nonebot_plugin_apscheduler/__init__.py", line 13, in <module>
    scheduler = AsyncIOScheduler()
  File "/usr/local/lib/python3.9/site-packages/apscheduler/schedulers/base.py", line 87, in __init__
    self.configure(gconfig, **options)
  File "/usr/local/lib/python3.9/site-packages/apscheduler/schedulers/base.py", line 131, in configure
    self._configure(config)
  File "/usr/local/lib/python3.9/site-packages/apscheduler/schedulers/asyncio.py", line 54, in _configure
    super(AsyncIOScheduler, self)._configure(config)
  File "/usr/local/lib/python3.9/site-packages/apscheduler/schedulers/base.py", line 701, in _configure
    self.timezone = astimezone(config.pop('timezone', None)) or get_localzone()
  File "/usr/local/lib/python3.9/site-packages/tzlocal/unix.py", line 203, in get_localzone
    _cache_tz = _get_localzone()
  File "/usr/local/lib/python3.9/site-packages/tzlocal/unix.py", line 180, in _get_localzone
    tz = pds.timezone(tzname)
  File "/usr/local/lib/python3.9/site-packages/pytz_deprecation_shim/_impl.py", line 41, in timezone
    raise get_exception(UnknownTimeZoneError, key)
pytz_deprecation_shim._exceptions._make_pytz_derived_errors.<locals>.UnknownTimeZoneError: ''
11-13 12:31:07 [ERROR] nonebot | Failed to import "nonebot_plugin_xiuxian"
Traceback (most recent call last):
  File "/root/??/bot_linux/bot.py", line 31, in <module>
    nonebot.load_plugin('nonebot_plugin_xiuxian')
  File "/usr/local/lib/python3.9/site-packages/nonebot/plugin/load.py", line 34, in load_plugin
    return manager.load_plugin(module_path)
> File "/usr/local/lib/python3.9/site-packages/nonebot/plugin/manager.py", line 141, in load_plugin
    module = importlib.import_module(name)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "/usr/local/lib/python3.9/site-packages/nonebot/plugin/manager.py", line 233, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/local/lib/python3.9/site-packages/nonebot_plugin_xiuxian/__init__.py", line 33, in <module>
    scheduler = require("nonebot_plugin_apscheduler").scheduler
  File "/usr/local/lib/python3.9/site-packages/nonebot/plugin/load.py", line 167, in require
    raise RuntimeError(f'Cannot load plugin "{name}"!')
RuntimeError: Cannot load plugin "nonebot_plugin_apscheduler"!

**Comment by Shinoakii** [comment]
我也不太清楚，可以尝试下在bot.py里先加载nonebot_plugin_apscheduler试试：
在nonebot.load_plugin('nonebot_plugin_xiuxian')先加载定时任务插件
这样
nonebot.load_plugin('nonebot_plugin_apscheduler')
nonebot.load_plugin('nonebot_plugin_xiuxian')

**Comment by BMC-Gordon0921** [comment]
> 我也不太清楚，可以尝试下在bot.py里先加载nonebot_plugin_apscheduler试试： 在nonebot.load_plugin('nonebot_plugin_xiuxian')先加载定时任务插件 这样 nonebot.load_plugin('nonebot_plugin_apscheduler') nonebot.load_plugin('nonebot_plugin_xiuxian')

问题得到解决，根据nonebot官方文档中对于定时任务的基本配置进行代码修改，将时区错误纠正，从而使每一个使用apscheduler插件的第三方库均可以正常使用（是的，所有使用这玩意的在纠正时区错误之前全爆红）
感谢佬提供的更新插件建议，在更新到0.2.0的apscheduler后，import error被纠正。
希望自己的掉坑经历可以帮助到需要的人！
和大佬贴贴——
【问题得到初步解决，本issue由发起人主动关闭。】
