### ISSUE TITLE
报错，调了很久没调好TAT

### ISSUE THREAD

**Issue by Solidal** [s52047qwas/nonebot_plugin_xiuxian#126]
01-17 11:53:25 [ERROR] nonebot | Failed to import "nonebot_plugin_xiuxian"
Traceback (most recent call last):
  File "C:\Users\28925\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\28925\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\28925\Desktop\nonebot2\venv\virtualenvs\nb2-oneclick-NbKNZaOC-py3.10\Scripts\nb.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "C:\Users\28925\Desktop\nonebot2\venv\virtualenvs\nb2-oneclick-NbKNZaOC-py3.10\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\28925\Desktop\nonebot2\venv\virtualenvs\nb2-oneclick-NbKNZaOC-py3.10\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\28925\Desktop\nonebot2\venv\virtualenvs\nb2-oneclick-NbKNZaOC-py3.10\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\28925\Desktop\nonebot2\venv\virtualenvs\nb2-oneclick-NbKNZaOC-py3.10\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\28925\Desktop\nonebot2\venv\virtualenvs\nb2-oneclick-NbKNZaOC-py3.10\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\28925\Desktop\nonebot2\venv\virtualenvs\nb2-oneclick-NbKNZaOC-py3.10\lib\site-packages\nb_cli\commands\main.py", line 30, in run
    run_bot(file, app)
  File "C:\Users\28925\Desktop\nonebot2\venv\virtualenvs\nb2-oneclick-NbKNZaOC-py3.10\lib\site-packages\nb_cli\handlers\deploy.py", line 20, in run_bot
    module = importlib.import_module(module_name)
  File "C:\Users\28925\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\28925\Desktop\nonebot2\.\bot.py", line 84, in <module>
    nonebot.load_from_toml("pyproject.toml")
  File "C:\Users\28925\Desktop\nonebot2\venv\virtualenvs\nb2-oneclick-NbKNZaOC-py3.10\lib\site-packages\nonebot\plugin\load.py", line 122, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "C:\Users\28925\Desktop\nonebot2\venv\virtualenvs\nb2-oneclick-NbKNZaOC-py3.10\lib\site-packages\nonebot\plugin\load.py", line 59, in load_all_plugins
    return manager.load_all_plugins()
  File "C:\Users\28925\Desktop\nonebot2\venv\virtualenvs\nb2-oneclick-NbKNZaOC-py3.10\lib\site-packages\nonebot\plugin\manager.py", line 168, in load_all_plugins
    return set(
  File "C:\Users\28925\Desktop\nonebot2\venv\virtualenvs\nb2-oneclick-NbKNZaOC-py3.10\lib\site-packages\nonebot\plugin\manager.py", line 169, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "C:\Users\28925\Desktop\nonebot2\venv\virtualenvs\nb2-oneclick-NbKNZaOC-py3.10\lib\site-packages\nonebot\plugin\manager.py", line 141, in load_plugin
    module = importlib.import_module(name)
  File "C:\Users\28925\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\Users\28925\Desktop\nonebot2\venv\virtualenvs\nb2-oneclick-NbKNZaOC-py3.10\lib\site-packages\nonebot\plugin\manager.py", line 233, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\28925\Desktop\nonebot2\venv\virtualenvs\nb2-oneclick-NbKNZaOC-py3.10\lib\site-packages\nonebot_plugin_xiuxian\__init__.py", line 28, in <module>
    from .utils import Txt2Img, data_check_conf, check_user_type, get_msg_pic, check_user
  File "C:\Users\28925\Desktop\nonebot2\venv\virtualenvs\nb2-oneclick-NbKNZaOC-py3.10\lib\site-packages\nonebot_plugin_xiuxian\utils.py", line 10, in <module>
    from PIL import Image, ImageDraw, ImageFont
ModuleNotFoundError: No module named 'PIL'

**Comment by Shinoakii** [comment]
pip install pillow
