### ISSUE TITLE
【报错】无法突破

### ISSUE THREAD

**Issue by Z735803792** [s52047qwas/nonebot_plugin_xiuxian#29]
终端如下
```
09-09 08:46:14 [ERROR] nonebot | Running matcher <Matcher from nonebot_plugin_xiuxian, type=message, priority=5, temp=False> failed.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/usr/lib/python3.9/multiprocessing/spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
  File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.9/dist-packages/uvicorn/_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/usr/local/lib/python3.9/dist-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.9/dist-packages/nonebot/message.py", line 146, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "/usr/local/lib/python3.9/dist-packages/nonebot/message.py", line 196, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/usr/local/lib/python3.9/dist-packages/nonebot/internal/matcher.py", line 672, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/usr/local/lib/python3.9/dist-packages/nonebot/internal/matcher.py", line 639, in simple_run
    await handler(
  File "/usr/local/lib/python3.9/dist-packages/nonebot/dependencies/__init__.py", line 92, in __call__
    return await self.call(**values)
  File "/usr/local/lib/python3.9/dist-packages/nonebot_plugin_xiuxian/__init__.py", line 390, in update_level
    level_rate = XiuxianJsonDate().level_rate(level_name)  #对应境界突破的概率
  File "/usr/local/lib/python3.9/dist-packages/nonebot_plugin_xiuxian/xiuxian2_handle.py", line 413, in level_rate
    return data[0][level]
KeyError: 0
```

**Comment by s52047qwas** [comment]
对应json文件及insatll版本已更新，最新版本为0.3.2，请替换即可
上述问题为json文件未更新，重新下载最新的json文件替换即可

**Comment by Z735803792** [comment]
谢大佬
